### ISSUE TITLE
Unsure how it compares to Bat

### ISSUE THREAD

**Issue by ngirard** [foxfriends/syncat#1]
Hi,

Unless I'm misunderstood, the most popular similar application in the Rust ecosystem is [Bat](https://github.com/sharkdp/bat).

It would be nice if you could outline the characteristics of your application relative to Bat, in the README.

Thanks !

**Comment by foxfriends** [comment]
I have added some information about the features, let me know if there are any other questions!

**Comment by ngirard** [comment]
Hey Cameron,

Thanks, this is nice. I like how you enumerated the characteristics while giving the related option at the same time!

I'm proposing a small addition related to the benefits brought by leveraging Tree-sitter, via #4.

Cheers
