### ISSUE TITLE
Provide default setting

### ISSUE THREAD

**Issue by Freed-Wu** [foxfriends/syncat#12]
[nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter) use tree-sitter to parse file, too, which provide [a default setting](https://github.com/nvim-treesitter/nvim-treesitter#supported-languages) for many languages. Can this project provide default setting when user doesn't have `~/.config/syncat`?

**Comment by foxfriends** [comment]
Released in 3.4.0:

When loading languages, if `~/.config/syncat/languages.toml` does not exist, it will fall back to the default (`syncat/config/languages.toml`)

When loading stylesheets, if `~/.config/syncat/style/active/{lang}.syncat` does not exist, it will fall back to the default (`syncat/config/style/active{lang}.syncat`). If that does not exist, then defaults to empty styles

**Comment by Freed-Wu** [comment]
<https://github.com/foxfriends/syncat/blob/master/syncat/config/languages.toml> only have ~50 languages. However, [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter#supported-languages) provides 134 languages. Is there any reason to not to provide extra languages such as cannot work?

**Comment by foxfriends** [comment]
There's no particular reason, feel free to make a PR adding more languages. The problem with just adding a language to the language.toml is that there will still be no highlighting until someone makes a stylesheet, which takes time and knowledge of the language, so I won't be adding many except for languages I use, otherwise they will be low quality highlights

**Comment by Freed-Wu** [comment]
> The problem with just adding a language to the language.toml is that there will still be no highlighting until someone makes a stylesheet

I see. Is it possible to generate sytlesheet from <https://github.com/nvim-treesitter/nvim-treesitter/tree/master/queries>?

**Comment by foxfriends** [comment]
Hmm possibly, I'll take a look and see
